Repository pagopa/pagopa-gpd-payments-pull, pull requests merged in 2024-07, with the labels that each got.

#13 [VAS-936] fix: Openapi
  README.md
  openapi/openapi.json
  src/main/java/it/gov/pagopa/gpd/payments/pull/App.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNotices.java
  src/main/resources/application.properties
Labels: size/small, patch

#12 [VAS-901] feat: introducing pull flag
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/repository/PaymentPositionRepository.java
Labels: enhancement, size/small, minor

#14 Logging kibana
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.uat
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/payments/pull/App.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/config/LoggingInterceptor.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNotices.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/service/impl/PaymentNoticesServiceImpl.java
  src/main/resources/application.properties
Labels: patch
