Repository pagopa/pagopa-gpd-payments-pull, pull requests merged in 2024-10, with the labels that each got.

#16 feat: Add apim test product
  infra/04_apim_api.tf
  infra/99_locals.tf
Labels: ignore-for-release

#15 [PPANTT-146] feat: Add performance test
  .devops/performance-test-pipelines.yml
  .github/workflows/code_review.yml
  README.md
  infra/policy/_base_policy.xml
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.uat
  integration-test/src/step_definitions/support/client/payment_pull_client.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/utility/request_builder.js
  openapi/openapi.json
  perfomance-test/README.md
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/gpd_client.js
  performance-test/src/modules/payment_pull_client.js
  performance-test/src/modules/util.js
  performance-test/src/package.json
  performance-test/src/payment_pull_service_test.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
  src/main/java/it/gov/pagopa/gpd/payments/pull/App.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/OpenApiGenerationTest.java
Labels: size/large, skip

#21 Configured performance test in prod
  .devops/performance-test-pipelines.yml
  docker/run_docker.sh
  infra/policy/_base_policy.xml
  performance-test/src/prod.environment.json
  performance-test/src/test-types/constant.json
Labels: size/small, patch

#22 Enabled apim test product in prod
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
Labels: ignore-for-release, size/small

#20 Performance test
  .devops/performance-test-pipelines.yml
  docker/run_docker.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  performance-test/src/payment_pull_service_test.js
  pom.xml
  src/main/java/it/gov/pagopa/gpd/payments/pull/App.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/config/Logged.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/config/LoggingInterceptor.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentOptionMetadata.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/Transfer.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/TransferMetadata.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/AppErrorException.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/PaymentNoticeException.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/repository/PaymentPositionRepository.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/Generic.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNotices.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/service/PaymentNoticesService.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/service/impl/PaymentNoticesServiceImpl.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/gpd/payments/pull/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/repository/PaymentPositionRepositoryTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/resources/GenericTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNoticesTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/service/impl/PaymentNoticesServiceImplTest.java
Labels: size/large, major

#24 Enable integration test notification
  .github/workflows/integration_test.yml
Labels: skip, ignore-for-release, size/small
