Repository pagopa/pagopa-gpd-payments-pull, pull requests merged in 2024-04, with the labels that each got.

#3 [VAS-729] feat: add payment notice service
  .github/workflows/code_review.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/payments/pull/App.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentOptionMetadata.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/Transfer.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/TransferMetadata.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/AppErrorException.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/InvalidTaxCodeHeaderException.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/PaymentNoticeException.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/mapper/PaymentNoticeMapper.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/ErrorResponse.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/Installment.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/PaymentNotice.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/PaymentOption.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/PaymentNoticeStatus.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/PaymentOptionStatus.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/TransferStatus.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/enums/Type.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/repository/PaymentPositionRepository.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/Generic.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNotices.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/service/PaymentNoticesService.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/service/impl/PaymentNoticesServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/messages.properties
  src/main/resources/resources-config.json
  src/test/java/it/gov/pagopa/gpd/payments/pull/Constants.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/repository/PaymentPositionRepositoryTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/resources/GenericTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNoticesTest.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/service/impl/PaymentNoticesServiceImplTest.java
Labels: enhancement, size/large, major

#4 fix: moved dockerfile to allow release
  .github/workflows/anchore.yml
  .github/workflows/release_deploy.yml
  Dockerfile
  agent/config.yaml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: bug, skip, size/small

#8 fix: github-action create agent
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.lock
  helm/Chart.yaml
  openapi/openapi.json
Labels: bug, size/small, patch

#6 [VAS-733] feat: add e2e tests
  .github/workflows/anchore.yml
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/01_github_environment.tf
  Dockerfile_integration_test
  docker/docker-compose.yml
  docker/run_docker.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/payment_notices.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/payment_notice_step.js
  integration-test/src/step_definitions/support/client/gpd_client.js
  integration-test/src/step_definitions/support/client/payment_pull_client.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/utility/axios_common.js
  integration-test/src/step_definitions/support/utility/data.js
  integration-test/src/step_definitions/support/utility/helpers.js
  integration-test/src/step_definitions/support/utility/request_builder.js
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/payments/pull/repository/PaymentPositionRepository.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNotices.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNoticesTest.java
Labels: enhancement, size/large, patch

#9 fix: installment mappings
  openapi/openapi.json
  src/main/java/it/gov/pagopa/gpd/payments/pull/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/mapper/PaymentNoticeMapper.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/Installment.java
  src/test/java/it/gov/pagopa/gpd/payments/pull/service/impl/PaymentNoticesServiceImplTest.java
Labels: size/small, patch

#10 Logging with Privacy
  openapi/openapi.json
  src/main/java/it/gov/pagopa/gpd/payments/pull/config/LoggingInterceptor.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/models/PaymentNotice.java
  src/main/java/it/gov/pagopa/gpd/payments/pull/resources/PaymentNotices.java
Labels: skip, size/small
